apiVersion: v1
kind: Service
metadata:
  name: spring-boot-todo-app
  labels:
    app: spring-boot-todo-app
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: spring-boot-todo-app