apiVersion: skaffold/v2beta14
kind: Config
metadata:
  name: spring-boot-todo-app
build:
  artifacts:
  - image: de.icr.io/station/spring-boot-app
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
    - k8s/service.yaml
